/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'People',
      items: [
        {
          type: 'doc',
          id: 'people/current'
        },
        {
          label: 'Alumni',
          type: 'doc',
          id: 'people/alumni',
        },
        { 
          label: 'Affiliations',
          type: 'doc',
          id: 'people/affiliations'
        },
        { 
          label: 'Sponsors',
          type: 'doc',
          id: 'people/sponsors'
        }
      ],
    },
    {
      type: 'category',
      label: 'Programs & Initiatives',
      items: [
        {
          type: 'doc',
          id: 'programs/programs',
        },
        {
          type: 'doc',
          id: 'programs/experiential_learning',
        },
        {
          type: 'doc',
          id: 'programs/consulting',
        },
        {
          type: 'doc',
          id: 'programs/advocacy',
        }
      ]
    },
    'portfolio',
  
    {
      type: 'category',
      label: 'Get Involved',
      items: [
        {
          label: 'Find out how to get involved',
          type: 'doc',
          id: 'engage/engage',
        },
        {
          label: 'Request software development',
          type: 'doc',
          id: 'engage/software',
        },
        {
          label: 'Join our community of developers',
          type: 'doc',
          id: 'engage/community',
        },
        {
          label: 'Partner with us',
          type: 'doc',
          id: 'engage/partner',
        },
        {
          label: 'Discover emerging talent',
          type: 'doc',
          id: 'engage/talent',
        },
        {
          label: 'Make a gift',
          type: 'doc',
          id: 'donate',
        },
      ],
    },
    {
      type: 'category',
      label: 'Open Resources',
      items: [
        {
          type: 'doc',
          id: 'resources/open/open',
        },
        {
          type: 'doc',
          id: 'resources/playbooks/playbook',
        },
        {
          type: 'doc',
          id: 'resources/role_guides/role_guides',
        },
      ]
    },
    'oss-across-slu',
    'donate',
  ],
  //  */
};

module.exports = sidebars;
