/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Programs & Initiatives',
      link: {type: 'doc', id: 'programs/programs'},
      items: [
        {
          type: 'category',
          label: 'Experiential Learning',
          link: {type: 'doc', id: 'programs/experiential_learning'},
          items: [
            {
              type: 'category',
              label: 'Opening Skills & Solutions',
              link: { type: 'doc', id: 'programs/oss/skills_solutions'},
              items: [
                { type: 'doc', id: 'programs/oss/how_it_works' },
                { type: 'doc', id: 'programs/oss/student_experience' },
                { type: 'doc', id: 'programs/oss/team_structure' },
                {
                  type: 'category',
                  label: 'CS Capstone',
                  link: { type: 'doc', id: 'programs/oss/capstone' },
                  items: [
                    { type: 'doc', id: 'programs/oss/capstone_dates', label: 'Dates & Timeline' },
                  ]
                },
                {
                  type: 'category',
                  label: 'Developing OSS Products',
                  link: { type: 'doc', id: 'programs/oss/dossp' },
                  items: [
                    { type: 'doc', id: 'programs/oss/dossp_dates', label: 'Dates & Timeline' },
                  ]
                },
                { type: 'doc', id: 'programs/oss/get_involved' },
              ]
            },
            {
              type: 'category',
              label: 'BOLT Workshop',
              link: { type: 'doc', id: 'programs/bolt/overview' },
              items: [
                { type: 'doc', id: 'programs/bolt/workshop', label: 'Workshop Content' },
                { type: 'doc', id: 'programs/bolt/participate', label: 'Participate' },
                { type: 'doc', id: 'programs/bolt/dates', label: 'Dates & Timeline' },
              ]
            },
            {
              type: 'category',
              label: 'Industry Fellows',
              link: { type: 'doc', id: 'programs/fellows/overview'},
              items: [
                { type: 'doc', id: 'programs/fellows/role', label: 'The Role' },
                { type: 'doc', id: 'programs/fellows/process_dates', label: 'Application Process' },
                { type: 'doc', id: 'programs/fellows/faq' },
                { type: 'doc', id: 'programs/fellows/apply' },
                { type: 'doc', id: 'programs/fellows/key_dates', label: 'Key Dates' },
              ]
            },
            {
              type: 'doc',
              id: 'programs/open_source_in_service'
            }
          ]
        },
        {
          type: 'doc',
          id: 'programs/consulting',
        },
        {
          type: 'doc',
          id: 'programs/advocacy',
        }
      ]
    },
    {
      type: 'category',
      label: 'Projects',
      items: [
        {
          label: 'Product Portfolio',
          type: 'doc',
          id: 'projects/portfolio',
        },
        {
          type: 'doc',
          id: 'projects/oss-across-slu',
        },
      ]
    },
    {
      type: 'category',
      label: 'Connect',
      items: [
        {
          label: 'Students',
          type: 'doc',
          id: 'connect_with/student_opportunities',
        },
        {
          label: 'Researchers',
          type: 'doc',
          id: 'connect_with/researcher_opportunities',
        },
        {
          label: 'Community',
          type: 'doc',
          id: 'connect_with/community_opportunities',
        },
        {
          label: 'Organizations',
          type: 'doc',
          id: 'connect_with/organization_opportunities',
        },
        {
          label: 'Volunteers',
          type: 'doc',
          id: 'connect_with/volunteer_opportunities',
        },
      ],
    },
    {
      type: 'category',
      label: 'Get Involved',
      items: [
        {
          type: 'category',
          label: 'Contribute',
          link: { type: 'doc', id: 'get_involved/contribute' },
          items: [
            {
              label: 'Contribute Code',
              type: 'doc',
              id: 'get_involved/community'
            },
            {
              label: 'Gain Experience',
              type: 'doc',
              id: 'get_involved/experience'
            },
            {
              label: 'Lead a Team',
              type: 'doc',
              id: 'get_involved/leadership'
            },
            {
              label: 'Mentor',
              type: 'doc',
              id: 'get_involved/mentor'
            },
          ]
        },
        {
          type: 'category',
          label: 'Partner',
          link: { type: 'doc', id: 'get_involved/partner' },
          items: [
            {
              label: 'Engage Programs',
              type: 'doc',
              id: 'get_involved/engage'
            },
            {
              label: 'Develop Software',
              type: 'doc',
              id: 'get_involved/solutions'
            },
            {
              label: 'Discover Talent',
              type: 'doc',
              id: 'get_involved/talent'
            },
            {
              label: 'Sponsor',
              type: 'doc',
              id: 'get_involved/sponsor'
            },
          ]
        },
        {
          type: 'category',
          label: 'Get Help',
          link: { type: 'doc', id: 'get_involved/get_help' },
          items: [
          {
            label: 'Research Software Consults',
            type: 'doc',
            id: 'get_involved/rse'
          },
          {
            label: 'Clinics and Workshops',
            type: 'doc',
            id: 'get_involved/training'
          },
          {
            label: 'Open Data Planning',
            type: 'doc',
            id: 'get_involved/data'
          },
          {
            label: 'Open Science',
            type: 'doc',
            id: 'get_involved/open_science'
          },
          ]
        },
        {
          label: 'Support Us',
          type: 'doc',
          id: 'get_involved/donate',
        },
      ],
    },
    {
      type: 'category',
      label: 'About',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'People',
          items: [
            {
              label: 'Leadership',
              type: 'doc',
              id: 'people/leadership'
            },
            {
              label: 'Staff',
              type: 'doc',
              id: 'people/staff',
            },
            {
              label: 'Contributors',
              type: 'doc',
              id: 'people/contributors'
            },
            {
              label: 'Affiliations',
              type: 'doc',
              id: 'people/affiliations'
            },
          ],
        },
        {
          type: 'category',
          label: 'Open Resources',
          items: [
            {
              type: 'doc',
              id: 'resources/open/open',
            },
            {
              type: 'doc',
              id: 'resources/playbooks/playbook',
            },
            {
              type: 'doc',
              id: 'resources/role_guides/role_guides',
            },
          ],
        },
      ],
    },
  ],
  //  */
  portfolioSidebar: [
    {
      type: 'ref',
      label: 'Programs & Initiatives',
      id: 'programs/programs',
    },
    {
      type: 'category',
      label: 'Projects',
      items: [
        {
          type: 'category',
          label: 'Product Portfolio',
          items: [
            {
              type: 'category',
              label: 'Active Products',
              items: [
                {
                  type: 'doc',
                  id: 'projects/baio/about',
                },
                {
                  type: 'doc',
                  id: 'projects/civickit/about',
                },
                {
                  type: 'doc',
                  id: 'projects/coredesk/about',
                },
                {
                  type: 'doc',
                  id: 'projects/cv_zebrafish/about',
                },
                {
                  type: 'doc',
                  id: 'projects/dads/about',
                },
                {
                  type: 'doc',
                  id: 'projects/digital_bone_box/about',
                },
                {
                  type: 'doc',
                  id: 'projects/droneworld/about',
                },
                {
                  type: 'doc',
                  id: 'projects/gradeval360/about',
                },
                {
                  type: 'doc',
                  id: 'projects/health_app/about',
                },
                {
                  type: 'doc',
                  id: 'projects/iperf/about',
                },
                {
                  type: 'doc',
                  id: 'projects/md/about',
                },
                {
                  type: 'doc',
                  id: 'projects/mechatronics_vr/about',
                },
                {
                  type: 'doc',
                  id: 'projects/mithridatium/about',
                },
                {
                  type: 'doc',
                  id: 'projects/morph/about',
                },
                {
                  type: 'doc',
                  id: 'projects/mouser/about',
                },
                {
                  type: 'doc',
                  id: 'projects/oss_cicd_automation/about',
                },
                {
                  type: 'doc',
                  id: 'projects/oss_cybersecurity/about',
                },
                {
                  type: 'doc',
                  id: 'projects/oss_dev_analytics/about',
                },
                {
                  type: 'doc',
                  id: 'projects/oss_infra_ops/about',
                },
                {
                  type: 'doc',
                  id: 'projects/pilot_data_synchronization/about',
                },
                {
                  type: 'doc',
                  id: 'projects/rerum_playground/about',
                },
                {
                  type: 'doc',
                  id: 'projects/rerum_server/about',
                },
                {
                  type: 'doc',
                  id: 'projects/saltify/about',
                },
                {
                  type: 'doc',
                  id: 'projects/shelter_volunteers/about',
                },
                {
                  type: 'doc',
                  id: 'projects/simulation_surgery/about',
                },
                {
                  type: 'doc',
                  id: 'projects/wheres_religion_desktop/about',
                },
                {
                  type: 'doc',
                  id: 'projects/wheres_religion_mobile/about',
                },
              ]
            },
            {
              type: 'category',
              label: 'Stable Products',
              items: [
                {
                  type: 'doc',
                  id: 'projects/bubblescan/about',
                },
                {
                  type: 'doc',
                  id: 'projects/deer/about-deer',
                },
                {
                  type: 'doc',
                  id: 'projects/esp/about',
                },
                {
                  type: 'doc',
                  id: 'projects/gallery_of_glosses/about',
                },
                {
                  type: 'doc',
                  id: 'projects/hpc_projects/about',
                },
                {
                  type: 'doc',
                  id: 'projects/innerpeacetime/about',
                },
                {
                  type: 'doc',
                  id: 'projects/iris/about',
                },
                {
                  type: 'doc',
                  id: 'projects/meltshiny/about',
                },
                {
                  type: 'doc',
                  id: 'projects/montis/about',
                },
                {
                  type: 'doc',
                  id: 'projects/pi4micronaut/about',
                },
                {
                  type: 'doc',
                  id: 'projects/rerum_geolocator/about',
                },
                {
                  type: 'doc',
                  id: 'projects/step_time_biofeedback/about',
                },
                {
                  type: 'doc',
                  id: 'projects/stl_data_api/about',
                },
                {
                  type: 'doc',
                  id: 'projects/tpen_interfaces/about',
                },
              ]
            },
            {
              type: 'category',
              label: 'Inactive Products',
              items: [
                {
                  type: 'link',
                  label: 'Congestion Control Emulator',
                  href: 'https://github.com/oss-slu/Congestion-control-emulator',
                },
                {
                  type: 'link',
                  label: 'Drone Swarm',
                  href: 'https://www.aircraft-lab.org/',
                },
                {
                  type: 'doc',
                  id: 'projects/ispraak/about',
                },
                {
                  type: 'link',
                  label: 'ML Code Generator',
                  href: 'https://github.com/oss-slu/ml_code_generator',
                },
                {
                  type: 'doc',
                  id: 'projects/open_energy_dashboard/about',
                },
                {
                  type: 'link',
                  label: 'Santiago',
                  href: 'https://github.com/oss-slu/Santiago',
                },
                {
                  type: 'doc',
                  id: 'projects/sib/about',
                },
              ]
            },
          ]
        },
        {
          type: 'ref',
          label: 'OSS across SLU',
          id: 'projects/oss-across-slu'
        },
        // {
        //   type: 'ref',
        //   label: 'Whitepapers',
        //   id: 'projects/oss-across-slu'
        // },
      ],
    },
    {
      type: 'ref',
      label: 'Connect',
      id: 'connect_with/student_opportunities',
    },
    {
      type: 'ref',
      label: 'Get Involved',
      id: 'get_involved/contribute',
    },
    {
      type: 'ref',
      label: 'Open Resources',
      id: 'resources/open/open',
    },
    {
      type: 'ref',
      label: 'People',
      id: 'people/leadership',
    },
  ],
};

module.exports = sidebars;
